spring:
  application:
    name: challenge

  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/challenge_db}
    username: ${PG_USER:challenge}
    password: ${PG_PASSWORD:challenge_2024}
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  springdoc:
    swagger-ui:
      path: /challenge.html
    api-docs:
      path: /challenge
    packages-to-scan: com.challenge.controllers

frontend:
  url: ${FRONTEND_URL:http://localhost:4200}

jasper:
  path: